version: "3.9"
services:
  attic:
    build: misc/attic
    env_file: ".env"
    volumes:
    - "./misc/attic-config:/etc/attic"
    environment:
    - PORT=80
    - HOST=0.0.0.0
    - MONGO_URI=mongodb://mongo:27017/attic
    - REDIS_URI=redis://redis_cache:6379/1
    - "LOG_LEVEL=debug"
    - "ROOT_GROUPS=service,root"
    ports:
      - "0.0.0.0:8203:80"
    links:
      - mongo
      - redis_cache
  web:
    build: .
    environment:
      - PORT=80
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongo:27017/attic
      - SESSION_REDIS_URI=redis://redis_cache:6379/1
      - SERVICE_OAUTH_REDIS_URI=redis://redis_cache:6379/3
      - BULL_REDIS_URI=redis://redos_mq:6379/0
    ports:
      - "5000:5000"
    links:
      - redis_cache
      - redis_mq
      - mongo
      - attic
  mongo:
    image: "mongo:4.4"
    ports:
      - "127.0.0.1:8201:27017"
    volumes:
      - mongo:/data/db
  redis_cache:
    image: "redis:6"
    command: "redis-server --save \"\ --appendonly no --maxmemory 128mb --maxmemory-policy allkeys-lru"
    ports:
      - "127.0.0.1:8202:6379"
  redis_mq:
    image: "redis:6"
    command: "redis-server --dir /data/redis_mq --appendonly yes --maxmemory 512mb --maxmemory-policy noeviction"
    ports:
      - "127.0.0.1:8204:6379"
    volumes:
      - redis_mq:/data/redis_mq
volumes:
  mongo:
  redis_mq:
