version: "3.9"
services:
  attic:
    build: misc/attic
    env_file: ".env"
    volumes:
      - "./misc/attic-config:/etc/attic"
    environment:
      - PORT=80
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://root:pR5frehACijUwr1JUguf@mongodb.shop.zacharyboyd.network:27017/thirdact-attic?authSource=admin
      - REDIS_URI=redis://gc.zb.gy:8202/1
      - "LOG_LEVEL=debug"
      - "ROOT_GROUPS=service,root"
    ports:
      - "0.0.0.0:8203:80"
  #    links:
  #      - mongo
  #      - redis
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
      - attic
  mongo:
    image: "mongo:5"
    ports:
      - "127.0.0.1:8201:27017"
    volumes:
      - mongo:/data/db
  redis:
    image: "redis:6"
    ports:
      - "127.0.0.1:8202:6379"
volumes:
  mongo:
